
const { 
  SNOWFLAKE_APP,
  SNOWFLAKE_USER,
  SNOWFLAKE_PASSWORD,
  SNOWFLAKE_ACCOUNT,
  SNOWFLAKE_DATABASE,
  SNOWFLAKE_SCHEMA
} = process.env;

const config = {
  PORT: process.env.PORT || '3005',
  SNOWFLAKE_APP,
  SNOWFLAKE_USER,
  SNOWFLAKE_PASSWORD,
  SNOWFLAKE_ACCOUNT,
  SNOWFLAKE_DATABASE,
  SNOWFLAKE_SCHEMA
};

export default config;