name: SimpleGoRest Build

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.21.8'
    - name: go test
      run: |
        cd simplegorest
        go test -v --cover
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: docker build && docker push
      run: |
        FULL_IMAGE=$REGISTRY/$IMAGE_NAME:simplegorest
        cd simplegorest 
        docker build -t $FULL_IMAGE .
        docker push $FULL_IMAGE

